/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misformularios;

import java.awt.Image;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class frmEliminacion extends javax.swing.JFrame {

    /**
     * Creates new form frmEliminacion
     */
    Connection con;
    Statement st;
    PreparedStatement pstmt;
    ResultSet rs;

    public frmEliminacion() {
        initComponents();

        setTitle("Área de eliminación");
        setSize(1170, 850);
        setLocation(45, 130);

        tfIdLuc.requestFocus();

        //deshabilita las acciones de copiar y pegar en el campo
        tfIdLuc.setTransferHandler(null);

        ImageIcon imagen13 = new ImageIcon(getClass().getResource("/misimagenes/x.png"));
        ImageIcon icono13 = new ImageIcon(imagen13.getImage().getScaledInstance(jlabelx.getWidth(), jlabelx.getHeight(), Image.SCALE_DEFAULT));
        jlabelx.setIcon(icono13);
        ImageIcon imagen14 = new ImageIcon(getClass().getResource("/misimagenes/luchadoraelim.PNG"));
        ImageIcon icono14 = new ImageIcon(imagen14.getImage().getScaledInstance(jlabelLucFem.getWidth(), jlabelLucFem.getHeight(), Image.SCALE_DEFAULT));
        jlabelLucFem.setIcon(icono14);
        ImageIcon imagen15 = new ImageIcon(getClass().getResource("/misimagenes/luchadorelim.PNG"));
        ImageIcon icono15 = new ImageIcon(imagen15.getImage().getScaledInstance(jlabelLucMas.getWidth(), jlabelLucMas.getHeight(), Image.SCALE_DEFAULT));
        jlabelLucMas.setIcon(icono15);

        tfIdCom.setTransferHandler(null);

        ImageIcon imagen16 = new ImageIcon(getClass().getResource("/misimagenes/x.png"));
        ImageIcon icono16 = new ImageIcon(imagen16.getImage().getScaledInstance(jlabelx1.getWidth(), jlabelx1.getHeight(), Image.SCALE_DEFAULT));
        jlabelx1.setIcon(icono16);
        ImageIcon imagen17 = new ImageIcon(getClass().getResource("/misimagenes/combatefemeninoeliminado.jpg"));
        ImageIcon icono17 = new ImageIcon(imagen17.getImage().getScaledInstance(jlabelComFem.getWidth(), jlabelComFem.getHeight(), Image.SCALE_DEFAULT));
        jlabelComFem.setIcon(icono17);
        ImageIcon imagen18 = new ImageIcon(getClass().getResource("/misimagenes/combatemasculinoeliminado.jpg"));
        ImageIcon icono18 = new ImageIcon(imagen18.getImage().getScaledInstance(jlabelComMas.getWidth(), jlabelComMas.getHeight(), Image.SCALE_DEFAULT));
        jlabelComMas.setIcon(icono18);

        ImageIcon imagen19 = new ImageIcon(getClass().getResource("/misimagenes/x.png"));
        ImageIcon icono19 = new ImageIcon(imagen19.getImage().getScaledInstance(jlabelx2.getWidth(), jlabelx2.getHeight(), Image.SCALE_DEFAULT));
        jlabelx2.setIcon(icono19);
        ImageIcon imagen20 = new ImageIcon(getClass().getResource("/misimagenes/eve1.JPG"));
        ImageIcon icono20 = new ImageIcon(imagen20.getImage().getScaledInstance(jlabelEve1.getWidth(), jlabelEve1.getHeight(), Image.SCALE_DEFAULT));
        jlabelEve1.setIcon(icono20);
        ImageIcon imagen21 = new ImageIcon(getClass().getResource("/misimagenes/eve2.JPG"));
        ImageIcon icono21 = new ImageIcon(imagen21.getImage().getScaledInstance(jlabelEve2.getWidth(), jlabelEve2.getHeight(), Image.SCALE_DEFAULT));
        jlabelEve2.setIcon(icono21);

        tfIdEve.setTransferHandler(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        tfIdLuc = new javax.swing.JTextField();
        jlabelLucFem = new javax.swing.JLabel();
        jlabelLucMas = new javax.swing.JLabel();
        btnEliminarLuc = new javax.swing.JButton();
        btnLimpiarLuc = new javax.swing.JButton();
        jlabelx = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jLabel12 = new javax.swing.JLabel();
        tfIdCom = new javax.swing.JTextField();
        jlabelComFem = new javax.swing.JLabel();
        jlabelComMas = new javax.swing.JLabel();
        btnEliminarCom = new javax.swing.JButton();
        btnLimpiarCom = new javax.swing.JButton();
        jlabelx1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        tfIdEve = new javax.swing.JTextField();
        jlabelEve1 = new javax.swing.JLabel();
        jlabelEve2 = new javax.swing.JLabel();
        btnEliminarEve = new javax.swing.JButton();
        btnLimpiarEve = new javax.swing.JButton();
        jlabelx2 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AR JULIAN", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ÁREA DE ELIMINACIÓN");
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("ID:");

        tfIdLuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIdLucKeyTyped(evt);
            }
        });

        jlabelLucFem.setText("jlabelluchadoraelim");
        jlabelLucFem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlabelLucMas.setText("jlabelluchadorelim");
        jlabelLucMas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnEliminarLuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarLuc.setText("ELIMINAR LUCHADOR/A");
        btnEliminarLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLucActionPerformed(evt);
            }
        });

        btnLimpiarLuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiarLuc.setText("LIMPIAR LUCHADOR/A");
        btnLimpiarLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarLucActionPerformed(evt);
            }
        });

        jlabelx.setText("jlabelx");
        jlabelx.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDesktopPane3.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(tfIdLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jlabelLucFem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jlabelLucMas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnEliminarLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnLimpiarLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jlabelx, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabelLucFem, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiarLuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarLuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfIdLuc))
                .addGap(18, 18, 18)
                .addComponent(jlabelLucMas, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelLucFem, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jlabelLucMas, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jlabelx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(112, 112, 112)
                .addComponent(btnEliminarLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnLimpiarLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        jTabbedPane3.addTab("ELIMINAR LUCHADOR/RA", jPanel5);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane5.setBackground(new java.awt.Color(0, 204, 153));

        jLabel12.setText("ID:");

        tfIdCom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIdComKeyTyped(evt);
            }
        });

        jlabelComFem.setText("jlabelcombateFem");
        jlabelComFem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlabelComMas.setText("jlabelcombateMas");
        jlabelComMas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnEliminarCom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarCom.setText("ELIMINAR COMBATE");
        btnEliminarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarComActionPerformed(evt);
            }
        });

        btnLimpiarCom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiarCom.setText("LIMPIAR COMBATE");
        btnLimpiarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarComActionPerformed(evt);
            }
        });

        jlabelx1.setText("jlabelx1");
        jlabelx1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDesktopPane5.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(tfIdCom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jlabelComFem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jlabelComMas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(btnEliminarCom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(btnLimpiarCom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jlabelx1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabelComFem, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiarCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfIdCom))
                .addGap(18, 18, 18)
                .addComponent(jlabelComMas, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelx1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelComFem, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jlabelComMas, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jlabelx1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(112, 112, 112)
                .addComponent(btnEliminarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnLimpiarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jDesktopPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        jTabbedPane3.addTab("ELIMINAR COMBATE", jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane6.setBackground(new java.awt.Color(0, 255, 204));

        jLabel13.setText("ID:");

        tfIdEve.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIdEveKeyTyped(evt);
            }
        });

        jlabelEve1.setText("jlabelEve1");
        jlabelEve1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlabelEve2.setText("jlabelEve2");
        jlabelEve2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnEliminarEve.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarEve.setText("ELIMINAR EVENTO");
        btnEliminarEve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEveActionPerformed(evt);
            }
        });

        btnLimpiarEve.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiarEve.setText("LIMPIAR EVENTO");
        btnLimpiarEve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEveActionPerformed(evt);
            }
        });

        jlabelx2.setText("jlabelx2");
        jlabelx2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDesktopPane6.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(tfIdEve, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jlabelEve1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jlabelEve2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(btnEliminarEve, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(btnLimpiarEve, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jlabelx2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabelEve1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiarEve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarEve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfIdEve))
                .addGap(18, 18, 18)
                .addComponent(jlabelEve2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelx2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelEve1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jlabelEve2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jlabelx2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdEve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(112, 112, 112)
                .addComponent(btnEliminarEve, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnLimpiarEve, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jDesktopPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        jTabbedPane3.addTab("ELIMINAR EVENTO", jPanel10);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 1030, 650));

        btnAtras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtras.setText("ATRÁS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 150, 87));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdLucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdLucKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_tfIdLucKeyTyped

    private void btnEliminarLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLucActionPerformed
        // TODO add your handling code here:
        if ("".equals(tfIdLuc.getText())) {
            JOptionPane.showMessageDialog(null, "Campo vacío, introduzca una ID");
        } else {
            int confirmado = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar el/la luchador/ra con la id " + tfIdLuc.getText() + "?");
            if (JOptionPane.OK_OPTION == confirmado) {
                //System.out.println("CONFIRMADO");
                try {
                    String url = "jdbc:mysql://localhost:3306/mymma";
                    String userName = "root";
                    String password = "";
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection(url, userName, password);
                    //COMPROBAMOS QUE EXISTE LA ID DEL LUCHADOR EN LA BBDD
                    st = con.createStatement();
                    rs = st.executeQuery("SELECT * FROM luchador");
                    boolean flag_id = true;
                    while (rs.next()) {
                        if (rs.getInt(1) != Integer.parseInt(tfIdLuc.getText())) {
                            flag_id = false;
                        } else {
                            flag_id = true;
                            break;
                        }
                    }
                    st.close();

                    //UN LUCHADOR SOLO SE ELIMINARÁ CUANDO NO ESTE PARTICIPANDO EN NINGUN COMBATE Y NO SEA CAMPEON(SIGUIENTE ST)
                    /*COMPROBAMOS SI LA ID DEL LUCHADOR SE ENCUENTRA EN UN COMBATE Y DEVOLVEMOS LA ID/IDS DE LOS COMBATES
                    PARA QUE CUANDO ELIMINE ESOS COMBATES PUEDA ELIMINAR EL LUCHADOR/RA*/
                    st = con.createStatement();
                    rs = st.executeQuery("SELECT * FROM combate");
                    boolean flag_luchador_en_combate = true;
                    ArrayList<Integer> arraylist_idCom = new ArrayList<>();
                    while (rs.next()) {
                        if (rs.getInt("idluchadorrojoCom") == Integer.parseInt(tfIdLuc.getText())) {
                            flag_luchador_en_combate = false;
                            arraylist_idCom.add(rs.getInt("idCom"));
                        }
                        if (rs.getInt("idluchadorazulCom") == Integer.parseInt(tfIdLuc.getText())) {
                            flag_luchador_en_combate = false;
                            arraylist_idCom.add(rs.getInt("idCom"));
                        }
                    }
                    st.close();

                    //COMPROBAMOS SI LA ID DEL LUCHADOR ES CAMPEON
                    st = con.createStatement();
                    rs = st.executeQuery("SELECT * FROM cinturon");
                    boolean flag_luchador_campeon = true;
                    while (rs.next()) {
                        if (rs.getInt("idluchadorcampeonCin") == Integer.parseInt(tfIdLuc.getText())) {
                            flag_luchador_campeon = false;
                            break;
                        }
                    }
                    st.close();

                    if (flag_id == true && flag_luchador_en_combate == true && flag_luchador_campeon == true) {
                        st = con.createStatement();
                        String sql = "DELETE FROM luchador "
                                + "WHERE idLuc='" + tfIdLuc.getText() + "'";
                        st.executeUpdate(sql);
                        st.close();
                        JOptionPane.showMessageDialog(null, "LUCHADOR/A ELIMINADO/A CORRECTAMENTE");
                        tfIdLuc.setEnabled(false);
                        btnEliminarLuc.setEnabled(false);
                    } else {
                        if (flag_id == false) {
                            JOptionPane.showMessageDialog(null, "Error: La ID de el/la luchador/a introducida (" + tfIdLuc.getText() + ") no existe en la BBDD");
                        }
                        if (flag_luchador_en_combate == false) {
                            String str_idCom = "";
                            for (int i = 0; i < arraylist_idCom.size(); i++) {
                                str_idCom = str_idCom + " " + arraylist_idCom.get(i);
                            }
                            JOptionPane.showMessageDialog(null, "Error: La ID de el/la luchador/a introducida (" + tfIdLuc.getText() + ") ha participado en combate/s, "
                                    + "por tanto elimine primero el/los combate/s (desde la pestaña 'ELIMINAR COMBATE') para poder eliminar a el/la luchador/ra"
                                    + "\nID/s de combate en los que ha participado el/la luchador/ra:\n" + str_idCom.trim());
                        }
                        if (flag_luchador_campeon == false) {
                            JOptionPane.showMessageDialog(null, "Error: La ID de el/la luchador/a introducida (" + tfIdLuc.getText() + ") es campeón/a, "
                                    + "cambie de campeón/a al cinturón para poder eliminar a el/la luchador/ra (desde la pestaña 'ÁREA DE MODIFICACIÓN' - 'MODIFICAR CAMPEÓN/A')");
                        }
                    }
                    con.close();

                } catch (ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null, "Error en conexión: ClassNotFoundException");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error en conexión: SQLException" + e);
                }
            } else {
                //System.out.println("NO CONFIRMADO");
            }
        }

    }//GEN-LAST:event_btnEliminarLucActionPerformed

    private void btnLimpiarLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLucActionPerformed
        // TODO add your handling code here:
        btnEliminarLuc.setEnabled(true);
        tfIdLuc.setEnabled(true);
        tfIdLuc.setText("");
        tfIdLuc.requestFocus();
    }//GEN-LAST:event_btnLimpiarLucActionPerformed

    private void tfIdComKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdComKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_tfIdComKeyTyped

    private void btnEliminarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComActionPerformed
        // TODO add your handling code here:
        if ("".equals(tfIdCom.getText())) {
            JOptionPane.showMessageDialog(null, "Campo vacío, introduzca una ID");
        } else {
            int confirmado = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar el combate con la id " + tfIdCom.getText() + "?");
            if (JOptionPane.OK_OPTION == confirmado) {
                //System.out.println("CONFIRMADO");
                try {
                    String url = "jdbc:mysql://localhost:3306/mymma";
                    String userName = "root";
                    String password = "";
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection(url, userName, password);
                    //COMPROBAMOS QUE EXISTE LA ID DEL COMBATE EN LA BBDD
                    st = con.createStatement();
                    rs = st.executeQuery("SELECT * FROM combate");
                    boolean flag_id = true;
                    while (rs.next()) {
                        if (rs.getInt(1) != Integer.parseInt(tfIdCom.getText())) {
                            flag_id = false;
                        } else {
                            flag_id = true;
                            break;
                        }
                    }
                    st.close();

                    if (flag_id == true) {
                        st = con.createStatement();
                        String sql = "DELETE FROM combate "
                                + "WHERE idCom='" + tfIdCom.getText() + "'";
                        st.executeUpdate(sql);
                        st.close();
                        JOptionPane.showMessageDialog(null, "COMBATE ELIMINADO CORRECTAMENTE");
                        tfIdCom.setEnabled(false);
                        btnEliminarCom.setEnabled(false);
                    } else {
                        if (flag_id == false) {
                            JOptionPane.showMessageDialog(null, "Error: La ID del combate introducida (" + tfIdCom.getText() + ") no existe en la BBDD");
                        }
                    }
                    con.close();

                } catch (ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null, "Error en conexión: ClassNotFoundException");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error en conexión: SQLException" + e);
                }
            } else {
                //System.out.println("NO CONFIRMADO");
            }
        }
    }//GEN-LAST:event_btnEliminarComActionPerformed

    private void btnLimpiarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarComActionPerformed
        // TODO add your handling code here:
        btnEliminarCom.setEnabled(true);
        tfIdCom.setEnabled(true);
        tfIdCom.setText("");
        tfIdCom.requestFocus();
    }//GEN-LAST:event_btnLimpiarComActionPerformed

    private void tfIdEveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdEveKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_tfIdEveKeyTyped

    private void btnEliminarEveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEveActionPerformed
        // TODO add your handling code here:
        if ("".equals(tfIdEve.getText())) {
            JOptionPane.showMessageDialog(null, "Campo vacío, introduzca una ID");
        } else {
            int confirmado = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar el evento con la id " + tfIdEve.getText() + "?\n"
                    + "***NOTA IMPORTANTE: Se eliminarán consigo todos los combates de dicho evento");
            if (JOptionPane.OK_OPTION == confirmado) {
                //System.out.println("CONFIRMADO");
                try {
                    String url = "jdbc:mysql://localhost:3306/mymma";
                    String userName = "root";
                    String password = "";
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection(url, userName, password);
                    //COMPROBAMOS QUE EXISTE LA ID DEL EVENTO EN LA BBDD
                    st = con.createStatement();
                    rs = st.executeQuery("SELECT * FROM evento");
                    boolean flag_id = true;
                    while (rs.next()) {
                        if (rs.getInt(1) != Integer.parseInt(tfIdEve.getText())) {
                            flag_id = false;
                        } else {
                            flag_id = true;
                            break;
                        }
                    }
                    st.close();

                    if (flag_id == true) {
                        //PRIMERO - ELIMINAMOS TODOS LOS COMBATES DE ESTE EVENTO
                        st = con.createStatement();
                        String sql = "DELETE FROM combate "
                                + "WHERE ideventoCom='" + tfIdEve.getText() + "'";
                        st.executeUpdate(sql);
                        st.close();

                        //SEGUNDO - ELIMINAMOS EL EVENTO
                        st = con.createStatement();
                        sql = "DELETE FROM evento "
                                + "WHERE idEve='" + tfIdEve.getText() + "'";
                        st.executeUpdate(sql);
                        st.close();
                        JOptionPane.showMessageDialog(null, "EVENTO ELIMINADO CORRECTAMENTE");
                        tfIdEve.setEnabled(false);
                        btnEliminarEve.setEnabled(false);
                    } else {
                        if (flag_id == false) {
                            JOptionPane.showMessageDialog(null, "Error: La ID del evento introducida (" + tfIdEve.getText() + ") no existe en la BBDD");
                        }
                    }
                    con.close();

                } catch (ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null, "Error en conexión: ClassNotFoundException");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error en conexión: SQLException" + e);
                }
            } else {
                //System.out.println("NO CONFIRMADO");
            }
        }
    }//GEN-LAST:event_btnEliminarEveActionPerformed

    private void btnLimpiarEveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEveActionPerformed
        // TODO add your handling code here:
        btnEliminarEve.setEnabled(true);
        tfIdEve.setEnabled(true);
        tfIdEve.setText("");
        tfIdEve.requestFocus();
    }//GEN-LAST:event_btnLimpiarEveActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGuia().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEliminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEliminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEliminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEliminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEliminacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminarCom;
    private javax.swing.JButton btnEliminarEve;
    private javax.swing.JButton btnEliminarLuc;
    private javax.swing.JButton btnLimpiarCom;
    private javax.swing.JButton btnLimpiarEve;
    private javax.swing.JButton btnLimpiarLuc;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel jlabelComFem;
    private javax.swing.JLabel jlabelComMas;
    private javax.swing.JLabel jlabelEve1;
    private javax.swing.JLabel jlabelEve2;
    private javax.swing.JLabel jlabelLucFem;
    private javax.swing.JLabel jlabelLucMas;
    private javax.swing.JLabel jlabelx;
    private javax.swing.JLabel jlabelx1;
    private javax.swing.JLabel jlabelx2;
    private javax.swing.JTextField tfIdCom;
    private javax.swing.JTextField tfIdEve;
    private javax.swing.JTextField tfIdLuc;
    // End of variables declaration//GEN-END:variables
}
