/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misformularios;

import com.mysql.cj.jdbc.exceptions.PacketTooBigException;
import java.awt.Image;
import java.io.*;
import javax.swing.filechooser.FileFilter;
import java.sql.*;
import java.text.ParseException;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Luis
 */
public class frmInsercion extends javax.swing.JFrame {

    ImageIcon imagen;
    byte[] datosimagen;

    Connection con;
    PreparedStatement pstmt;
    ResultSet rs;

    /**
     * Creates new form frmInsercion
     */
    public frmInsercion() {
        initComponents();

        setTitle("Área de inserción");
        setSize(1170, 850);
        setLocation(45, 130);

        rbMasculinoLuc.setSelected(true);
        tfCategoriaLuc.setEnabled(false);
        rbRecordNoLuc.setSelected(true);
        tfTotalLuc.setEnabled(false);
        tfVictLuc.setEnabled(false);
        tfDerroLuc.setEnabled(false);
        rbMasculinoLuc.requestFocus();

        //deshabilita las acciones de copiar y pegar en el campo
        tfNombreLuc.setTransferHandler(null);
        tfPaisLuc.setTransferHandler(null);
        tfTotalLuc.setTransferHandler(null);
        tfVictLuc.setTransferHandler(null);
        tfDerroLuc.setTransferHandler(null);

        rbMasculinoArb.setSelected(true);
        ImageIcon imagen22 = new ImageIcon(getClass().getResource("/misimagenes/referee1.JPG"));
        ImageIcon icono22 = new ImageIcon(imagen22.getImage().getScaledInstance(jlabelreferee1.getWidth(), jlabelreferee1.getHeight(), Image.SCALE_DEFAULT));
        jlabelreferee1.setIcon(icono22);
        ImageIcon imagen23 = new ImageIcon(getClass().getResource("/misimagenes/referee2.JPG"));
        ImageIcon icono23 = new ImageIcon(imagen23.getImage().getScaledInstance(jlabelreferee2.getWidth(), jlabelreferee2.getHeight(), Image.SCALE_DEFAULT));
        jlabelreferee2.setIcon(icono23);

        tfNombreArb.setTransferHandler(null);

        ((JLabel) cbEquipoLuc.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        rbMasculinoLuc = new javax.swing.JRadioButton();
        rbFemeninoLuc = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tfNombreLuc = new javax.swing.JTextField();
        dcFechaLuc = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPaisLuc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfApodoLuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbEquipoLuc = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tfPesoLuc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCategoriaLuc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbRecordSiLuc = new javax.swing.JRadioButton();
        rbRecordNoLuc = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        tfTotalLuc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfVictLuc = new javax.swing.JTextField();
        tfDerroLuc = new javax.swing.JTextField();
        jcbInactivoLuc = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelFotoLuc = new javax.swing.JLabel();
        btnCargarLuc = new javax.swing.JButton();
        btnInsertarLuc = new javax.swing.JButton();
        btnLimpiarLuc = new javax.swing.JButton();
        sAlturaLuc = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rbMasculinoArb = new javax.swing.JRadioButton();
        rbFemeninoArb = new javax.swing.JRadioButton();
        tfNombreArb = new javax.swing.JTextField();
        jlabelreferee1 = new javax.swing.JLabel();
        jlabelreferee2 = new javax.swing.JLabel();
        btnInsertarArb = new javax.swing.JButton();
        btnLimpiarArb = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AR JULIAN", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ÁREA DE INSERCIÓN");
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SEXO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbMasculinoLuc);
        rbMasculinoLuc.setText("MASCULINO");
        jPanel2.add(rbMasculinoLuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        buttonGroup1.add(rbFemeninoLuc);
        rbFemeninoLuc.setText("FEMENINO");
        jPanel2.add(rbFemeninoLuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel2.setText("NOMBRE:");

        tfNombreLuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreLucKeyTyped(evt);
            }
        });

        dcFechaLuc.setDateFormatString("yyyy-MM-dd");

        jLabel3.setText("FECHA DE NACIMIENTO:");

        jLabel4.setText("PAÍS DE ORIGEN:");

        tfPaisLuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPaisLucKeyTyped(evt);
            }
        });

        jLabel5.setText("APODO DE LUCHADOR/RA:");

        jLabel6.setText("EQUIPO DE ENTRENAMIENTO:");

        cbEquipoLuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECCIONAR>", "EQUIPO GRIS", "EQUIPO NARANJA", "EQUIPO VERDE", "EQUIPO VIOLETA" }));

        jLabel7.setText("PESO (EN KG):");

        tfPesoLuc.setText("0");
        tfPesoLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoLucActionPerformed(evt);
            }
        });

        jLabel8.setText("CATEGORÍA:");

        jLabel9.setText("ALTURA (EN CM):");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "¿POSEE ALGÚN RÉCORD DE COMBATES?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(rbRecordSiLuc);
        rbRecordSiLuc.setText("SÍ");
        rbRecordSiLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRecordSiLucActionPerformed(evt);
            }
        });
        jPanel3.add(rbRecordSiLuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 23, -1, -1));

        buttonGroup2.add(rbRecordNoLuc);
        rbRecordNoLuc.setText("NO");
        rbRecordNoLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRecordNoLucActionPerformed(evt);
            }
        });
        jPanel3.add(rbRecordNoLuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 23, -1, -1));

        jLabel13.setText("Nº TOTAL:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 20));

        tfTotalLuc.setText("0");
        tfTotalLuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTotalLucKeyTyped(evt);
            }
        });
        jPanel3.add(tfTotalLuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 60, -1));

        jLabel14.setText("Nº DE VICTORIAS:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel15.setText("Nº DE DERROTAS:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        tfVictLuc.setText("0");
        tfVictLuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfVictLucKeyTyped(evt);
            }
        });
        jPanel3.add(tfVictLuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 60, -1));

        tfDerroLuc.setText("0");
        tfDerroLuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDerroLucKeyTyped(evt);
            }
        });
        jPanel3.add(tfDerroLuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 60, -1));

        jcbInactivoLuc.setText("INACTIVO");

        jLabel10.setText("¿POSEE ALGUNA LESIÓN O ESTÁ INACTIVO?");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "FOTO LUCHADOR/RA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFotoLuc.setText("Vista previa");
        panelFotoLuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.add(panelFotoLuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 280));

        btnCargarLuc.setText("CARGAR FOTO");
        btnCargarLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarLucActionPerformed(evt);
            }
        });

        btnInsertarLuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInsertarLuc.setText("INSERTAR LUCHADOR/RA");
        btnInsertarLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarLucActionPerformed(evt);
            }
        });

        btnLimpiarLuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiarLuc.setText("LIMPIAR LUCHADOR/RA");
        btnLimpiarLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarLucActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tfNombreLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(dcFechaLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tfPaisLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tfApodoLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cbEquipoLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tfPesoLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tfCategoriaLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbInactivoLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCargarLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnInsertarLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnLimpiarLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(sAlturaLuc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfPesoLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfCategoriaLuc))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(sAlturaLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfPaisLuc))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(dcFechaLuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfNombreLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbEquipoLuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfApodoLuc))))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbInactivoLuc))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btnCargarLuc)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btnInsertarLuc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiarLuc))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbInactivoLuc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNombreLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcFechaLuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfPaisLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfApodoLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnCargarLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbEquipoLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfPesoLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(tfCategoriaLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(sAlturaLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertarLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 630));

        jTabbedPane1.addTab("INSERTAR LUCHADOR/RA", jPanel1);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane2.setBackground(new java.awt.Color(0, 204, 153));

        jLabel11.setText("NOMBRE:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SEXO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup3.add(rbMasculinoArb);
        rbMasculinoArb.setText("MASCULINO");
        jPanel6.add(rbMasculinoArb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        buttonGroup3.add(rbFemeninoArb);
        rbFemeninoArb.setText("FEMENINO");
        jPanel6.add(rbFemeninoArb, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        tfNombreArb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreArbKeyTyped(evt);
            }
        });

        jlabelreferee1.setText("jlabelreferee1");
        jlabelreferee1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlabelreferee2.setText("jlabelreferee2");
        jlabelreferee2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnInsertarArb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInsertarArb.setText("INSERTAR ÁRBITRO/A");
        btnInsertarArb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarArbActionPerformed(evt);
            }
        });

        btnLimpiarArb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiarArb.setText("LIMPIAR ÁRBITRO/A");
        btnLimpiarArb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarArbActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(tfNombreArb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jlabelreferee1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jlabelreferee2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnInsertarArb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnLimpiarArb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jlabelreferee2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiarArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertarArb, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jlabelreferee1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(tfNombreArb, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(293, 293, 293))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfNombreArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlabelreferee1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jlabelreferee2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnInsertarArb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnLimpiarArb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel5.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        jTabbedPane1.addTab("INSERTAR ÁRBITRO/A", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 1030, 650));

        btnAtras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtras.setText("ATRÁS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 150, 87));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRecordNoLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRecordNoLucActionPerformed
        // TODO add your handling code here:
        tfTotalLuc.setEnabled(false);
        tfTotalLuc.setText("0");
        tfVictLuc.setEnabled(false);
        tfVictLuc.setText("0");
        tfDerroLuc.setEnabled(false);
        tfDerroLuc.setText("0");
    }//GEN-LAST:event_rbRecordNoLucActionPerformed

    private void rbRecordSiLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRecordSiLucActionPerformed
        // TODO add your handling code here:
        tfTotalLuc.setEnabled(true);
        tfTotalLuc.setText("");
        tfVictLuc.setEnabled(true);
        tfVictLuc.setText("");
        tfDerroLuc.setEnabled(true);
        tfDerroLuc.setText("");
        tfTotalLuc.requestFocus();
    }//GEN-LAST:event_rbRecordSiLucActionPerformed

    private void btnCargarLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarLucActionPerformed
        // TODO add your handling code here:
        if (btnCargarLuc == evt.getSource()) {
            File archivofoto;
            JFileChooser explorer = new JFileChooser();

            //filtro para que explore solo archivos imagen
            FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
            explorer.setFileFilter(imageFilter);

            int opcion = explorer.showOpenDialog(this);

            imagen = null;

            if (opcion == JFileChooser.APPROVE_OPTION) {
                archivofoto = explorer.getSelectedFile();
                imagen = new ImageIcon(archivofoto.getAbsolutePath());

                //Las siguientes 3 líneas ajusta la imagen cargada al tamaño del jlabel
                Image imageget = imagen.getImage();
                Image newimg = imageget.getScaledInstance(panelFotoLuc.getWidth(), panelFotoLuc.getHeight(), Image.SCALE_DEFAULT);
                imagen = new ImageIcon(newimg);

                panelFotoLuc.setIcon(imagen);

                try {
                    FileInputStream byteImagen = new FileInputStream(archivofoto);

                    long tam = archivofoto.length();
                    datosimagen = new byte[(int) tam];
                    byteImagen.read(datosimagen);

                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnCargarLucActionPerformed

    private void btnInsertarLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarLucActionPerformed
        // TODO add your handling code here:

        boolean flag_edad = false;
        try {
            if (dcFechaLuc.getDate() != null) {
                String formato = dcFechaLuc.getDateFormatString();
                Date date = dcFechaLuc.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String fnacimi = String.valueOf(sdf.format(date));
                Date fechautildate = sdf.parse(fnacimi);
                java.sql.Date fechasqldate = new java.sql.Date(fechautildate.getYear(), fechautildate.getMonth(), fechautildate.getDate());
                //LINEAS PARA OBTENER LA EDAD A TRAVES DE LA FECHA DE NACIMIENTO
                Date fechanacim = fechasqldate;
                DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate fechaNac = LocalDate.parse(fechanacim.toString(), fmt);
                LocalDate currentDate = LocalDate.now();
                Period periodo = Period.between(fechaNac, currentDate);
                int edad_actual = periodo.getYears();
                //RANGO DE EDADES VÁLIDAS: DE 18 HASTA LOS 100 AÑOS
                if (edad_actual < 18 || edad_actual > 100) {
                    flag_edad = true;
                } else {
                    flag_edad = false;
                }
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error: ParseException");
        }

        boolean flag_altura = false;
        int alturaint = Integer.parseInt(sAlturaLuc.getValue().toString());
        if (alturaint < 100 || alturaint > 250 && alturaint != 0) {
            if (alturaint == 0) {
                flag_altura = false;
            } else {
                flag_altura = true;
            }
        }

        int flagint_record_empty;
        if ("".equals(tfTotalLuc.getText()) || "".equals(tfVictLuc.getText()) || "".equals(tfDerroLuc.getText())) {
            flagint_record_empty = 1;
        } else if (Integer.parseInt(tfTotalLuc.getText()) != Integer.parseInt(tfVictLuc.getText()) + Integer.parseInt(tfDerroLuc.getText())) {
            flagint_record_empty = 2;
        } else {
            flagint_record_empty = 3;
        }

        if ("".equals(tfNombreLuc.getText()) || dcFechaLuc.getDate() == null || flag_edad == true || "".equals(tfPaisLuc.getText()) || "".equals(tfApodoLuc.getText()) || cbEquipoLuc.getSelectedIndex() == 0
                || "0".equals(tfPesoLuc.getText()) || "".equals(tfCategoriaLuc.getText()) || alturaint == 0 || flag_altura == true || flagint_record_empty == 1 || flagint_record_empty == 2 || imagen == null) {
            if ("".equals(tfNombreLuc.getText())) {
                JOptionPane.showMessageDialog(null, "El campo 'NOMBRE' está vacío");
            }
            if (dcFechaLuc.getDate() == null) {
                JOptionPane.showMessageDialog(null, "El campo 'FECHA DE NACIMIENTO' está vacío o marque una fecha válida");
            }
            if (flag_edad == true) {
                JOptionPane.showMessageDialog(null, "Error en el campo 'FECHA DE NACIMIENTO': Rango de edades válidas, desde los 18 hasta los 100 años\nMarque otra fecha");
            }
            if ("".equals(tfPaisLuc.getText())) {
                JOptionPane.showMessageDialog(null, "El campo 'PAÍS DE ORIGEN' está vacío");
            }
            if ("".equals(tfApodoLuc.getText())) {
                JOptionPane.showMessageDialog(null, "El campo 'APODO DEL LUCHADOR' está vacío");
            }
            if (cbEquipoLuc.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Error en el campo 'EQUIPO DE ENTRENAMIENTO': Seleccione un equipo");
            }
            if ("0".equals(tfPesoLuc.getText())) {
                JOptionPane.showMessageDialog(null, "El campo 'PESO' está a cero, introduzca un peso válido:\nPara luchadores: de 52.3 a 120.2kg\nPara luchadoras: de 48 a 65.6kg");
            }
            if ("".equals(tfCategoriaLuc.getText())) {
                JOptionPane.showMessageDialog(null, "El campo 'CATEGORÍA' está vacío: Para rellenarlo una vez introducido el 'PESO', desde esa casilla, presione la tecla Enter\nRangos de pesos válidos:\nPara luchadores: de 52.3 a 120.2kg\nPara luchadoras: de 48 a 65.6kg");
            }
            if (alturaint == 0) {
                JOptionPane.showMessageDialog(null, "El campo 'ALTURA' está a cero");
            }
            if (flag_altura == true) {
                JOptionPane.showMessageDialog(null, "Error en el campo 'ALTURA': rango de estaturas válidas de 100 a 250cm");
            }
            if (flagint_record_empty == 1) {
                JOptionPane.showMessageDialog(null, "Compruebe que los campos 'Nº TOTAL', 'Nº DE VICTORIAS' y 'Nº DE DERROTAS' no estén vacíos");
            }
            if (flagint_record_empty == 2) {
                JOptionPane.showMessageDialog(null, "Error en el campo 'Nº TOTAL': No coincide la suma de victorias y derrotas con los combates totales");
            }
            if (imagen == null) {
                JOptionPane.showMessageDialog(null, "Error en el campo 'FOTO LUCHADOR/RA': Cargue una foto desde 'CARGAR FOTO'");
            }
        } else {
            try {
                String sexo = "";
                if (rbMasculinoLuc.isSelected()) {
                    sexo = rbMasculinoLuc.getText();
                } else if (rbFemeninoLuc.isSelected()) {
                    sexo = rbFemeninoLuc.getText();
                }

                String estado;
                if (jcbInactivoLuc.isSelected()) {
                    estado = "INACTIVO";
                } else {
                    estado = "ACTIVO";
                }

                String formato = dcFechaLuc.getDateFormatString();
                Date date = dcFechaLuc.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String fnacim = String.valueOf(sdf.format(date));
                Date fechautildate = sdf.parse(fnacim);
                java.sql.Date fechasqldate = new java.sql.Date(fechautildate.getYear(), fechautildate.getMonth(), fechautildate.getDate());

                String url = "jdbc:mysql://localhost:3306/mymma";
                String userName = "root";
                String password = "";
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(url, userName, password);
                String sql = "INSERT INTO luchador (sexoLuc, nombreLuc, fechadenacimientoLuc, "
                        + "paisLuc, apodoLuc, equipodeentrenamientoLuc, pesoLuc, categoriaLuc, alturaLuc, "
                        + "numerodecombatesLuc, numerodevictoriasLuc, numerodederrotasLuc, estadoLuc, "
                        + "fotoLuc) "
                        + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                pstmt = con.prepareStatement(sql);

                pstmt.setString(1, sexo);
                pstmt.setString(2, tfNombreLuc.getText().toUpperCase());
                pstmt.setDate(3, fechasqldate);
                pstmt.setString(4, tfPaisLuc.getText().toUpperCase());
                pstmt.setString(5, tfApodoLuc.getText().toUpperCase());
                pstmt.setString(6, cbEquipoLuc.getSelectedItem().toString());
                pstmt.setFloat(7, Float.parseFloat(tfPesoLuc.getText()));
                pstmt.setString(8, tfCategoriaLuc.getText());
                pstmt.setInt(9, Integer.parseInt(sAlturaLuc.getValue().toString()));
                pstmt.setInt(10, Integer.parseInt(tfTotalLuc.getText()));
                pstmt.setInt(11, Integer.parseInt(tfVictLuc.getText()));
                pstmt.setInt(12, Integer.parseInt(tfDerroLuc.getText()));
                pstmt.setString(13, estado);

                if (imagen != null) {
                    pstmt.setBytes(14, datosimagen);
                } else {
                    pstmt.setBytes(14, null);
                }

                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "LUCHADOR/A INSERTADO/A CORRECTAMENTE");
                btnInsertarLuc.setEnabled(false);

                tfNombreLuc.setEnabled(false);
                dcFechaLuc.setEnabled(false);
                tfPaisLuc.setEnabled(false);
                tfApodoLuc.setEnabled(false);
                cbEquipoLuc.setEnabled(false);
                sAlturaLuc.setEnabled(false);
                rbRecordSiLuc.setEnabled(false);
                rbRecordNoLuc.setEnabled(false);
                tfTotalLuc.setEnabled(false);
                tfVictLuc.setEnabled(false);
                tfDerroLuc.setEnabled(false);
                jcbInactivoLuc.setEnabled(false);
                btnCargarLuc.setEnabled(false);

                pstmt.close();
                con.close();

            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Error: ParseException");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Error: Compruebe que en los campos 'Nº TOTAL', 'Nº DE VICTORIAS' y 'Nº DE DERROTAS' sólo se hayan introducido números");
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Error en conexión: ClassNotFoundException");
            } catch (PacketTooBigException e) {
                JOptionPane.showMessageDialog(null, "Error en el campo 'FOTO LUCHADOR/RA': Foto demasiado grande, cargue una foto más pequeña");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error en conexión: SQLException " + e);
            }
        }


    }//GEN-LAST:event_btnInsertarLucActionPerformed

    private void btnLimpiarLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLucActionPerformed
        // TODO add your handling code here:
        rbMasculinoLuc.setSelected(true);
        tfNombreLuc.setText("");
        dcFechaLuc.setDate(null);
        tfPaisLuc.setText("");
        tfApodoLuc.setText("");
        cbEquipoLuc.setSelectedIndex(0);
        tfPesoLuc.setEnabled(true);
        tfPesoLuc.setText("0");
        tfCategoriaLuc.setText("");
        sAlturaLuc.setValue(0);
        rbRecordNoLuc.setSelected(true);
        tfTotalLuc.setText("0");
        tfTotalLuc.setEnabled(false);
        tfVictLuc.setText("0");
        tfVictLuc.setEnabled(false);
        tfDerroLuc.setText("0");
        tfDerroLuc.setEnabled(false);
        jcbInactivoLuc.setSelected(false);
        panelFotoLuc.setIcon(null);
        datosimagen = null;
        btnInsertarLuc.setEnabled(true);
        rbMasculinoLuc.requestFocus();
        rbMasculinoLuc.setEnabled(true);
        rbFemeninoLuc.setEnabled(true);

        tfNombreLuc.setEnabled(true);
        dcFechaLuc.setEnabled(true);
        tfPaisLuc.setEnabled(true);
        tfApodoLuc.setEnabled(true);
        cbEquipoLuc.setEnabled(true);
        sAlturaLuc.setEnabled(true);
        rbRecordSiLuc.setEnabled(true);
        rbRecordNoLuc.setEnabled(true);
        jcbInactivoLuc.setEnabled(true);
        btnCargarLuc.setEnabled(true);
        imagen = null;
    }//GEN-LAST:event_btnLimpiarLucActionPerformed

    private void tfPesoLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoLucActionPerformed
        // TODO add your handling code here:
        try {
            double peso = Double.parseDouble(tfPesoLuc.getText());
            if (rbMasculinoLuc.isSelected()) {
                if (peso < 52.3 || peso > 120.2) {
                    JOptionPane.showMessageDialog(null, "Introduzca un peso válido: de 52.3 a 120.2kg");
                } else {
                    if (peso >= 52.3 && peso < 56.7) {
                        tfCategoriaLuc.setText("PESO MOSCA");
                    }
                    if (peso >= 56.7 && peso < 61.2) {
                        tfCategoriaLuc.setText("PESO GALLO");
                    }
                    if (peso >= 61.2 && peso < 65.7) {
                        tfCategoriaLuc.setText("PESO PLUMA");
                    }
                    if (peso >= 65.7 && peso < 70.3) {
                        tfCategoriaLuc.setText("PESO LIGERO");
                    }
                    if (peso >= 70.3 && peso < 77.1) {
                        tfCategoriaLuc.setText("PESO WELTER");
                    }
                    if (peso >= 77.1 && peso < 83.9) {
                        tfCategoriaLuc.setText("PESO MEDIO");
                    }
                    if (peso >= 83.9 && peso < 92.9) {
                        tfCategoriaLuc.setText("PESO SEMICOMPLETO");
                    }
                    if (peso >= 92.9 && peso <= 120.2) {
                        tfCategoriaLuc.setText("PESO PESADO");
                    }
                    tfPesoLuc.setEnabled(false);
                    rbMasculinoLuc.setEnabled(false);
                    rbFemeninoLuc.setEnabled(false);
                }
            } else {
                if (peso < 48 || peso > 65.6) {
                    JOptionPane.showMessageDialog(null, "Introduzca un peso válido: de 48 a 65.6kg");
                } else {
                    if (peso >= 48 && peso < 52.3) {
                        tfCategoriaLuc.setText("PESO PAJA");
                    }
                    if (peso >= 52.3 && peso < 56.7) {
                        tfCategoriaLuc.setText("PESO MOSCA");
                    }
                    if (peso >= 56.7 && peso < 61.2) {
                        tfCategoriaLuc.setText("PESO GALLO");
                    }
                    if (peso >= 61.2 && peso <= 65.6) {
                        tfCategoriaLuc.setText("PESO PLUMA");
                    }
                    tfPesoLuc.setEnabled(false);
                    rbMasculinoLuc.setEnabled(false);
                    rbFemeninoLuc.setEnabled(false);
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error en el campo 'PESO': Compruebe que sólo se hayan introducido números");
        }
    }//GEN-LAST:event_tfPesoLucActionPerformed

    private void tfPaisLucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPaisLucKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (car != ' ' && car < 'A' || car > 'Z' && car < 'a' || car > 'z' && car != 'ñ' && car != 'Ñ') {
            evt.consume();
        }
    }//GEN-LAST:event_tfPaisLucKeyTyped

    private void btnLimpiarArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarArbActionPerformed
        // TODO add your handling code here:
        rbMasculinoArb.setSelected(true);
        tfNombreArb.setText("");
        rbMasculinoArb.requestFocus();
        btnInsertarArb.setEnabled(true);
        rbMasculinoArb.setEnabled(true);
        rbFemeninoArb.setEnabled(true);
        tfNombreArb.setEnabled(true);
    }//GEN-LAST:event_btnLimpiarArbActionPerformed

    private void btnInsertarArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarArbActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnInsertarArb) {
            try {
                String url = "jdbc:mysql://localhost:3306/mymma";
                String userName = "root";
                String password = "";
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(url, userName, password);

                String sexo = "";
                if (rbMasculinoArb.isSelected()) {
                    sexo = rbMasculinoArb.getText();
                } else if (rbFemeninoArb.isSelected()) {
                    sexo = rbFemeninoArb.getText();
                }

                if ("".equals(tfNombreArb.getText())) {
                    if ("".equals(tfNombreArb.getText())) {
                        JOptionPane.showMessageDialog(null, "El campo 'NOMBRE' está vacío");
                    }
                } else {
                    String sql = "INSERT INTO arbitro (sexoArb, nombreArb) "
                            + "VALUES (?,?)";
                    pstmt = con.prepareStatement(sql);

                    pstmt.setString(1, sexo);
                    pstmt.setString(2, tfNombreArb.getText().toUpperCase());

                    pstmt.executeUpdate();

                    JOptionPane.showMessageDialog(null, "ÁRBITRO/A INSERTADO/A CORRECTAMENTE");
                    btnInsertarArb.setEnabled(false);

                    rbMasculinoArb.setEnabled(false);
                    rbFemeninoArb.setEnabled(false);
                    tfNombreArb.setEnabled(false);

                    pstmt.close();
                    con.close();
                }
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Error en conexión: ClassNotFoundException");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error en conexión: SQLException " + e);
            }
        }
    }//GEN-LAST:event_btnInsertarArbActionPerformed

    private void tfNombreLucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreLucKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (car != ' ' && car < 'A' || car > 'Z' && car < 'a' || car > 'z' && car != 'ñ' && car != 'Ñ') {
            evt.consume();
        }
    }//GEN-LAST:event_tfNombreLucKeyTyped

    private void tfNombreArbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreArbKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (car != ' ' && car < 'A' || car > 'Z' && car < 'a' || car > 'z' && car != 'ñ' && car != 'Ñ') {
            evt.consume();
        }
    }//GEN-LAST:event_tfNombreArbKeyTyped

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGuia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGuia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGuia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGuia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGuia().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void tfTotalLucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTotalLucKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_tfTotalLucKeyTyped

    private void tfVictLucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVictLucKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_tfVictLucKeyTyped

    private void tfDerroLucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDerroLucKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_tfDerroLucKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInsercion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInsercion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInsercion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInsercion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInsercion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCargarLuc;
    private javax.swing.JButton btnInsertarArb;
    private javax.swing.JButton btnInsertarLuc;
    private javax.swing.JButton btnLimpiarArb;
    private javax.swing.JButton btnLimpiarLuc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbEquipoLuc;
    private com.toedter.calendar.JDateChooser dcFechaLuc;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jcbInactivoLuc;
    private javax.swing.JLabel jlabelreferee1;
    private javax.swing.JLabel jlabelreferee2;
    private javax.swing.JLabel panelFotoLuc;
    private javax.swing.JRadioButton rbFemeninoArb;
    private javax.swing.JRadioButton rbFemeninoLuc;
    private javax.swing.JRadioButton rbMasculinoArb;
    private javax.swing.JRadioButton rbMasculinoLuc;
    private javax.swing.JRadioButton rbRecordNoLuc;
    private javax.swing.JRadioButton rbRecordSiLuc;
    private javax.swing.JSpinner sAlturaLuc;
    private javax.swing.JTextField tfApodoLuc;
    private javax.swing.JTextField tfCategoriaLuc;
    private javax.swing.JTextField tfDerroLuc;
    private javax.swing.JTextField tfNombreArb;
    private javax.swing.JTextField tfNombreLuc;
    private javax.swing.JTextField tfPaisLuc;
    private javax.swing.JTextField tfPesoLuc;
    private javax.swing.JTextField tfTotalLuc;
    private javax.swing.JTextField tfVictLuc;
    // End of variables declaration//GEN-END:variables
}
